name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*' # Activates only with a new version tag (es. v1.0.0)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write   # OIDC authentication
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # not necessarily matching the library .net version 

      - name: Create clean NuGet.config (v3 only)
        run: |
          cat <<EOF > NuGet.config
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <add key="nuget" value="https://api.nuget.org/v3/index.json" />
            </packageSources>
          </configuration>
          EOF

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build ./Bodde.Common.Extensions/Bodde.Common.Extensions.csproj --configuration Release

      - name: Pack NuGet package
        run: dotnet pack ./Bodde.Common.Extensions/Bodde.Common.Extensions.csproj --configuration Release --output ./nupkg

      - name: Publish to NuGet using OIDC
        run: dotnet nuget push "./nupkg/*.nupkg" --configfile NuGet.config --skip-duplicate
